name: "Build OpenSSL - Windows (x64)"

on:
  workflow_dispatch:

# https://github.com/openssl/openssl/blob/master/.github/workflows/windows.yml
jobs:
  build:
  
    strategy:
      matrix:
        platform:

          - arch: arm64
            os: windows-2025
            vcvars: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat

          - arch: amd64
            os: windows-2025
            vcvars: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat

          - arch: x86
            os: windows-2025
            vcvars: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat

    runs-on: ${{ matrix.platform.os }}

    steps:

      - name: Setup NASM
        shell: pwsh
        run: |
          choco install nasm ${{ matrix.platform.arch == 'x86' && '--x86' || '' }}
          "C:\Program Files${{ matrix.platform.arch == 'x86' && ' (x86)' || '' }}\NASM" >> $env:GITHUB_PATH

      - name: Checkout OpenSSL
        uses: actions/checkout@v6
        with:
          repository: openssl/openssl
          submodules: true
          ref: openssl-3.6.2

      - name: Prepare Build
        run: mkdir build

      - name: Configure Build
        working-directory: build
        shell: cmd
        run: |
          call "${{ matrix.platform.vcvars }}"
          perl ..\Configure --banner=Configured --strict-warnings -DOSSL_WINCTX=openssl no-makedepend
          perl configdata.pm --dump

      - name: Build
        working-directory: build
        shell: cmd
        run: |
          call "${{ matrix.platform.vcvars }}"
          nmake /S

      - name: Test
        working-directory: build
        shell: cmd
        run: |
          call "${{ matrix.platform.vcvars }}"
          nmake test HARNESS_JOBS=4

      - name: Install
        working-directory: build
        shell: cmd
        run: |
          call "${{ matrix.platform.vcvars }}"
          mkdir dist
          nmake install DESTDIR=dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: build/dist

